### ISSUE TITLE
Research flexbox vs css grids

### ISSUE THREAD

**Issue by dimitraz** [slant-website/breakpoint.css#4]
**Description**
Provide a list of pros and cons and practical & reproducible examples of using css grids vs using flexbox under the hood (containers, grids, banners, vertical alignment, etc)

**Comment by kingsleyzissou** [comment]
This is a good article:

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Relationship_of_Grid_Layout

**Comment by kingsleyzissou** [comment]
Also this, she visual shows the differences:
https://youtu.be/hs3piaN4b5I

**Comment by kingsleyzissou** [comment]
CSS grid has the same vertical and horizontal properties of flex box. But have a look at those links and see which you prefer.

Getting a staggered grid would be easier with css grid, but it depends what we’re going for
