### ISSUE TITLE
To JS or not to JS

### ISSUE THREAD

**Issue by kingsleyzissou** [slant-website/breakpoint.css#5]
This is a simple one really. Some components may require some JavaScript. Do we:

1. Exclude the component altogether? 
2. Build the necessary classes like .hidden and .visible and leave the JS implementation to the user. This way the framework would be lighter and it would be front-end framework agnostic?
3. Build a basic Vanilla JavaScript script for these components?

**Comment by dimitraz** [comment]
hmm good point. I think for the absolute essential initially javascript won't be necessary. We'll be able to do a lot just with css. When it becomes a necessity we can come back and discuss a plan. What do you think?

**Comment by dimitraz** [comment]
what do you think @kingsleyzissou @piccolazucca?

**Comment by kingsleyzissou** [comment]
Yeah I agree with you, I'll close this issue for now. JS won't be necessary for now.
