### ISSUE TITLE
Css vs Sass re-hash

### ISSUE THREAD

**Issue by kingsleyzissou** [slant-website/breakpoint.css#6]
Milena brought up a valid point about not using Sass, one of them was variables. So if we wanted to change the colours across the whole framework etc. Another benefit of Sass would be the vendor auto-prefixes (which I guess we could do in editor). But I think it's worth raising the question before we get started and making sure that we are sure, rather then making technology choice changes down the line.

**Comment by dimitraz** [comment]
Hmm good points guys. Let's go with Sass for now then?

**Comment by dimitraz** [comment]
Sass it is then, closing this for now 👍
